apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: manas-user-service
spec:
  selector:
    matchLabels:
      app: manas-user-service
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: manas-user-service
    spec:
      containers:
        - name: manas-user-service
          image: manas-user-service:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Never
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster