apiVersion: apps/v1
kind: Deployment
metadata:
  name: h2db-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manas-h2db-service
  template:
    metadata:
      labels:
        app: manas-h2db-service
    spec:
      containers:
        - name: manas-h2db-service
          image: manas-h2db-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9082
          resources:
            requests:
              cpu: 200m # Customize these as needed
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          env: # Add environment variables if needed
            - name: DB_HOST
              value: manas-h2db-service # Assuming you create a Service for H2

      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
