apiVersion: v1
kind: Service
metadata:
  name: manas-h2db-service
spec:
  selector:
    app: manas-h2db-service # Adjust label if needed
  type: ClusterIP # Internal visibility only
  ports:
    - port: 9082 # Assuming H2 exposes port 9082
      targetPort: 9082
