apiVersion: v1
kind: Service
metadata:
  name: manas-wallet-service
spec:
  selector:
    app: manas-wallet-service
  type: LoadBalancer # Expose externally (optional)
  ports:
    - port: 8080 # External port (optional)
      targetPort: 8080 # Book service port
